spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/eBankiBoot
    username: postgres
    password: astayoucode
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

server:
  port: 8082


devtools:
  restart:
    enabled: false
